version: "3.9"

services:
  cassandra:
    container_name: oauth_cassandra
    image: cassandra:4.0
    ports:
      - 9042:9042
    volumes:
      - ./docker/cassandra:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=docker
